CREATE DATABASE TaskManagerDb 

GO

USE TaskManagerDb

CREATE TABLE TaskModels
(
	Id BIGINT IDENTITY,
	Title NVARCHAR(150) NOT NULL,
	[Description] NVARCHAR(500) NULL,
	[DateTime] DATETIME2 NOT NULL,
	[Priority] TINYINT NOT NULL,
	[Status] TINYINT NOT NULL
)